### ISSUE TITLE
payload = [object Object]

### ISSUE THREAD

**Issue by steven-tailor** [cdmbase/graphql-nats-subscriptions#5]
when publishing event by native nats client and payload type is object in the async iterator gets payload [object Object]

**Comment by SebT** [comment]
Same issue here with the following setup :

```js
new NatsPubSub({
	client: connect({
		url: 'my server url',
		json: true
	}),
	logger
});
```

**Comment by SebT** [comment]
When I receive an event, it is correctly logged by https://github.com/cdmbase/graphql-nats-subscriptions/blob/master/src/nats-pubsub.ts#L142 (i see a json object logged as message). But JSON.parse fails.

I think it's an issue with the published version on npm. In your `src/nats-pubsub`, I see that you DO NOT call `.toString` on the message variable. But in my project's node_modules, the file `dist/nats-pubsub.js` has an onMessage method like this :

```js
   onMessage(topic, message) {
        this.logger.trace('triggered onMessage with topic (%s), message (%j)', topic, message);
        const subscribers = this.subsRefsMap[topic];
        if (!subscribers || !subscribers.length) {
            return;
        }
        const messageString = message.toString(this.parseMessageWithEncoding);
        let parsedMessage;
        try {
            parsedMessage = JSON.parse(messageString);
        }
        catch (e) {
            parsedMessage = messageString;
        }
        for (const subId of subscribers) {
            const listener = this.subscriptionMap[subId][1];
            this.logger.trace('subscription listener to run for subId (%s)', subId);
            listener(parsedMessage);
        }
    }
```

which is totally different from https://github.com/cdmbase/graphql-nats-subscriptions/blob/master/src/nats-pubsub.ts#L141

**EDIT:** I confirm this. The dist folder published to npm does not match the version from src. Maybe you ran `npm publish` without running `npm run build` first for the 1.4.1 version ?

Proof: Installing the module from https://github.com/SebT/graphql-nats-subscriptions (I just commited the dist folder) instead of npm registry works fine

**Comment by veeramarni** [comment]
closing as it is not an issue with the npm package.
